---
title: "Elastic Net Analysis (Version 1.2)"
author: "Elyas Heidari"
date: "9/6/2018"
output:
  BiocStyle::html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packagees
```{r packages, message=FALSE, warning=FALSE, paged.print=FALSE}
library(Vennerable)
library(UpSetR)
library(FDb.InfiniumMethylation.hg19)
library(tidyverse)
library(reshape2)
library(limma)
library(GenomicRanges)
library(DESeq2)
library(pROC)
library(ggplot2)
library(beeswarm)
library(plyr)
library(jyluMisc)
library(glmnet)
```

# Functions
```{r funcitons, message=FALSE, warning=FALSE, paged.print=FALSE}
labeler <- function(x){
  x[x==0] <- "Res.WT"
  x[x==1] <- "Sens.WT"
  x[x==2] <- "Mut"
  factor(x)
}

diff.cont <- function(df, cnt){
  lev <- levels(factor(cnt))
  design <- model.matrix(~0+factor(cnt))
  colnames(design) <- c(as.character(lev[1]),as.character(lev[2]))
  contrast <- makeContrasts(g0 - g1, levels = design)
  fit <- lmFit(t(df), design)
  fit <- contrasts.fit(fit, contrast)
  fit <- eBayes(fit, 0.01)
  tT <- topTable(fit, adjust="fdr", sort.by="B", number=10000)
  tT
}

diff_count <- function(df1, df2, f){
  df1 <- df1[rownames(df1) %in% rownames(df2),]
  f_temp <- df2[rownames(df1), f]
  tt <- diff.cont(df1, paste0("g",f_temp))
  tt
}

top_sel <- function(tt, frac = 0.1){
  rownames(tt)[head(order(tt$adj.P.Val), (dim(tt)[1]*frac))]
}

enricher <- function(DEres, name, gmt){
  to.ret <- list()
  res <- data.matrix(DEres)
  res <- data.frame(res)
  res$symbol <- rownames(DEres)
  print(res$P.Value)
  res <- res %>% dplyr::filter(P.Value < 0.05)
  print(res)
  res$P.Value <- res$P.Value * sign(res$logFC)
  res <- res %>% dplyr::select(P.Value, symbol) 
  colnames(res)[1] <- "stat"
  res <- res %>% arrange(desc(stat))
  rownames(res) <- res$symbol
  res$symbol <- NULL
  print(res)
  rg <- runGSEA(inputTab = res, gmtFile = gmts[[gmt]])
  # rg$Name <- gsub(paste0(name, "_"),"", rg$Name)
  rg <- list(rg)
  names(rg) <- name
  to.ret$rg <- rg
  to.ret$enBar <- plotEnrichmentBar(resTab = rg, pCut = .2, ifFDR = FALSE, setName = gmt)
  to.ret
}

path.sel <- function(res){
  colnames(res)[c(4,6)] <- c("p.up", "p.down")
  res %>% dplyr::filter(p.up < 0.2 | p.down < 0.2) -> res
  res$Name
}

sel.nut <- function(df, spl, nut, TP53, lambda, alpha){
  md1 <-
    glmnet(
    data.matrix(df),
    as.factor(TP53),
    family = "binomial",
    lambda = lambda,
    alpha = alpha,
    intercept=FALSE
    )
  
  cf <- coef(md1)
  imp <- colnames(df)[cf@i]
  imp.df <- df[TP53 == 1,imp]
    
  md1 <-
    glmnet(
    data.matrix(imp.df),
    as.factor(nut[TP53 == 1]),
    family = "binomial",
    lambda = lambda,
    alpha = 1,
    intercept = FALSE
    )
  cf <- coef(md1)
  cf
}



sel.group <- function(df, spl, nut, TP53, lambda, alpha){
  md1 <-
    glmnet(
    data.matrix(df),
    as.factor(TP53),
    family = "binomial",
    lambda = lambda,
    alpha = alpha,
    intercept=FALSE
    )
  
  cf <- coef(md1)
  imp <- colnames(df)[cf@i]
    
  md1 <-
    glmnet(
    data.matrix(imp),
    as.factor(nut),
    family = "multinomial",
    lambda = lambda,
    alpha = 1,
    intercept = FALSE
    )
  cf <- coef(md1)
  cf
}

sel.Nutlin <- function(df, spl, nut, TP53, lambda, alpha){
  md1 <-
    glmnet(
    data.matrix(df),
    as.factor(TP53),
    family = "binomial",
    lambda = lambda,
    alpha = alpha,
    intercept=FALSE
    )
  
  cf <- coef(md1)
  imp <- colnames(df)[cf@i]
  imp.df <- df[TP53 == 1,imp]
    
  md1 <-
    glmnet(
    data.matrix(imp.df),
    as.numeric(nut[TP53 == 1]),
    family = "gaussian",
    lambda = lambda,
    alpha = 1,
    intercept = FALSE
    )
  cf <- coef(md1)
  cf
}

sel.rate <- function(x){
  sum(x != 0)
}

mean.rate <- function(x){
  (mean(x != 0)) * ifelse(mean(x) > 0, 1, -1)
}

se <- function(x){
  (sd(x != 0))
}

ens2sym <- function(vec){
  cols <- c("SYMBOL", "GENENAME")
  mapping <- AnnotationDbi::select(org.Hs.eg.db, keys=vec, columns=cols, keytype="ENSEMBL")
  mapping <- mapping %>% dplyr::group_by(ENSEMBL) %>% dplyr::summarize(sample(SYMBOL, 1)) 
  colnames(mapping)[2] <- "SYMBOL"
  rownames(mapping) <- mapping$ENSEMBL
  to.ret <- mapping[vec,]$SYMBOL
  names(to.ret) <- vec
  to.ret
}

```

# Load Preprocessed Data
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
load("../data/metadata/patmeta_180504.RData")
load("../data/Objects/exprMat.RData")
load("../data/Objects/CPS1000.RData")
load("../data/Objects/ic50.RData")
load("../data/Objects/meth.RData")
```

# Datasets
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
vennList <- Venn(list(metadata = patMeta$Patient.ID[!is.na(patMeta$TP53)], RNAseq = colnames(exprMat), CPS1000 = rownames(cps.data), methylation = rownames(meth.df)))
Vennerable::plot(vennList, doWeights = F, type = "ellipses", show = list(Faces = FALSE))

upset(fromList(list(metadata = patMeta$Patient.ID[!is.na(patMeta$TP53)], RNAseq = colnames(exprMat), CPS1000 = rownames(cps.data), methylation = rownames(meth.df), IC50 = rownames(ic50.data))), order.by = "freq", number.angles = 30, point.size = 3.5, line.size = 2, sets.bar.color = "orange")

colnames(ic50.data) <- make.names(colnames(ic50.data))
```

# Preprocess Data
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
patMeta <- data.frame(patMeta)
patMeta <- patMeta[!is.na(patMeta$TP53),]
rownames(patMeta) <- patMeta$Patient.ID
colnames(patMeta) <- make.names(colnames(patMeta))
colnames(cps.data) <- make.names(colnames(cps.data))
drug_meta <- merge(patMeta, cps.data, by = 0)
drug_meta <- drug_meta[,which(!colnames(drug_meta) %in% c("RO5963", "DMSO", "PBS"))]
rownames(drug_meta) <- drug_meta$Patient.ID
drug_meta <- drug_meta[,-c(1:3)]
exprMat <- data.frame(exprMat)
exprMat <- exprMat[which(!grepl("^ENS", rownames(exprMat))),]
```


# Define Cut-off for Nutlin Resistency
```{r}
my_roc <- roc(predictor = drug_meta$Nutlin.3a, response = drug_meta$TP53)
cut.off <- coords(my_roc, "best", ret = "threshold")
cut.off

plot.roc(
  predictor = drug_meta$Nutlin.3a,
  x = drug_meta$TP53,
  print.auc = TRUE,
  auc.polygon = F,
  grid = c(0.1, 0.2),
  grid.col = c("green", "red"),
  max.auc.polygon = TRUE,
  auc.polygon.col = "blue",
  print.thres = TRUE)

outliers <- rownames(drug_meta)[which(drug_meta$TP53 == 0 & drug_meta$Nutlin.3a >= 0.9)]
  
drug_meta$nut <- ifelse(rownames(drug_meta) %in% outliers, 1, 0)

beeswarm <- beeswarm(
  Nutlin.3a ~ TP53,
  data = drug_meta,
  method = 'swarm',
  pwcol = as.numeric(drug_meta$TP53) - as.numeric(drug_meta$nut),
  do.plot = F
)[, c(1, 2, 4)]
colnames(beeswarm) <- c("x", "y", "group")
beeswarm$group <- labeler(beeswarm$group)


beeswarm.plot <- ggplot(beeswarm, aes(x, y)) +
  xlab("") +
  scale_y_continuous(expression("Nutlin.3a Averaged")) + 
  geom_boxplot(aes(x, y, group = ifelse(group %in% c("Res.WT", "Sens.WT"), "WT", "Mut")), outlier.shape = NA) +
  geom_point(aes(colour = factor(group))) +
  scale_x_continuous(
  breaks = c(1:2),
  labels = c("unmutated", "mutated"),
  expand = c(0, 0.3)
  ) + geom_segment(aes(
    x = 0.8,
    y = cut.off,
    xend = 1.2,
    yend = cut.off,
    fill = "black"
  ), linetype = "dashed") +
  theme_bw() +
  labs(x = "TP53", col = "annotation")

beeswarm.plot
```


```{r}
# sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
# feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
# feature.df <- muvis::data_preproc(feature.df)
# feature.df <- feature.df[,-5183]
# mf <- muvis::min_forest(feature.df)

```


# Differential Analysis with Limma
```{r message=FALSE, warning=FALSE, paged.print=FALSE}

load("../data/results_genes.RData")

expr_TP53 <- results$TP53$rdf
genes <- rownames(expr_TP53)
genes <- ens2sym(genes)
genes <- genes[which(!is.na(genes))]
expr_TP53 <- expr_TP53[names(genes),]
rownames(expr_TP53) <- genes
colnames(expr_TP53)[6] <- "adj.P.Val"
colnames(expr_TP53)[5] <- "P.Value"
colnames(expr_TP53)[2] <- "logFC"
TP53.top <- results$TP53$results.df
top_expr_TP53 <- TP53.top[TP53.top$padj < 0.05 & abs(TP53.top$log2FoldChange) > 1,]
top_expr_TP53 <- ens2sym(rownames(top_expr_TP53))
top_expr_TP53 <- top_expr_TP53[which(!is.na(top_expr_TP53))]


expr_nut <- results$nut.res$rdf
genes <- rownames(expr_nut)
genes <- ens2sym(genes)
genes <- genes[which(!is.na(genes))]
expr_nut <- expr_nut[names(genes),]
rownames(expr_nut) <- genes
colnames(expr_nut)[6] <- "adj.P.Val"
colnames(expr_nut)[5] <- "P.Value"
colnames(expr_nut)[2] <- "logFC"
nut.top <- results$nut.res$results.df
top_expr_nut <- nut.top[nut.top$padj < 0.05 & abs(nut.top$log2FoldChange) > 1,]
top_expr_nut <- ens2sym(rownames(top_expr_nut))
top_expr_nut <- top_expr_nut[which(!is.na(top_expr_nut))]

# 
nut.top <- results$nut.res$results.df
nut.top <- nut.top[!is.na(nut.top$padj),]
top_expr_TP53 <- nut.top[nut.top$padj < 0.1,]

TP53.rdf <- results$TP53$rdf
nut.rdf <- results$nut.res$rdf
TP53.top <- results$TP53$results.df
TP53.top <- TP53.top[TP53.top$padj < 0.05 & abs(TP53.top$log2FoldChange) > 1,]
nut.top <- results$nut.res$results.df
nut.top <- nut.top[!is.na(nut.top$padj),]
nut.top <- nut.top[nut.top$padj < 0.1,]


drug_nut <- diff_count(cps.data, drug_meta[which(drug_meta$TP53 == 0),], "nut")
drug_TP53 <- diff_count(cps.data, patMeta, "TP53")
meth_nut <- diff_count(meth.df, drug_meta[which(drug_meta$TP53 == 0),], "nut")
meth_TP53 <- diff_count(meth.df, patMeta, "TP53")
expr_nut <- diff_count(t(exprMat), drug_meta[which(drug_meta$TP53 == 0),], "nut")
expr_TP53 <- diff_count(t(exprMat), patMeta, "TP53")
top_sel(drug_nut)
top_sel(drug_TP53)
top_meth_nut <- top_sel(meth_nut, 0.05)
top_meth_TP53 <- top_sel(meth_TP53, 0.05)
# top_expr_nut <- top_sel(expr_nut, 0.05)
# top_expr_TP53 <- top_sel(expr_TP53, 0.05)
top_drug_nut <- top_sel(drug_nut, 0.2)
top_drug_TP53 <- top_sel(drug_TP53, 0.2)



vennList <- Venn(list(methylation_nut = top_meth_nut , methylation_TP53 = top_meth_TP53, expression_nut = top_expr_nut, expression_TP53 = top_expr_TP53))
Vennerable::plot(vennList, doWeights = F, type = "ellipses", show = list(Faces = FALSE))

upset(fromList(list(methylation_nut = top_meth_nut , methylation_TP53 = top_meth_TP53, expression_nut = top_expr_nut, expression_TP53 = top_expr_TP53)), order.by = "freq", number.angles = 30, point.size = 3.5, line.size = 2, sets.bar.color = "blue")
```

# Drugs
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
drug.annotation <- read.csv("../data/TP53/targetAnnotation_all.csv", sep = ";")
drug.annotation$nameEMBL2016 <- gsub(x = drug.annotation$nameEMBL2016, pattern = " +", replacement = ".")


drug.annotation_nut <- drug.annotation[drug.annotation$nameCPS1000 %in% top_drug_nut | drug.annotation$nameEMBL2016 %in% top_drug_nut,]
targets_nut <- strsplit(as.character(drug.annotation_nut$target), ", ")
targets_nut <- unlist(targets_nut)

drug.annotation_TP53 <- drug.annotation[drug.annotation$nameCPS1000 %in% top_drug_TP53 | drug.annotation$nameEMBL2016 %in% top_drug_TP53,]
targets_TP53 <- strsplit(as.character(drug.annotation_TP53$target), ", ")
targets_TP53 <- unlist(targets_TP53)


vennList <- Venn(list(drug_nut = targets_nut , drug_TP53 = targets_TP53))
Vennerable::plot(vennList, doWeights = F, show = list(Faces = FALSE))

upset(fromList(list(expression_nut = top_expr_nut, expression_TP53 = top_expr_TP53, drug_nut = targets_nut, drug_TP53 = targets_TP53)), order.by = "freq", number.angles = 30, point.size = 3.5, line.size = 2, sets.bar.color = "blue")

# genes <- Reduce(union, list(expression_nut = top_expr_nut, expression_TP53 = top_expr_TP53, top_meth_nut, top_meth_TP53))

DA.features <- Reduce(union, list(expression_nut = top_expr_nut, expression_TP53 = top_expr_TP53, top_meth_nut, top_meth_TP53, top_drug_nut, top_drug_nut))
# sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
# feature.df <- cbind(drug_meta[sample.names,], t(exprMat[genes,sample.names]))
# feature.df <- muvis::data_preproc(feature.df)
# muvis::min_forest(feature.df[,-c(823:dim(feature.df)[2])])


```


# Gene Set Enrichment Analysis
```{r fig.height=13, message=FALSE, warning=FALSE, paged.print=FALSE}
gmts <- list(HALLMARK=system.file("extdata","h.all.v5.1.symbols.gmt",package="BloodCancerMultiOmics2017"),
             ONCOGENIC=system.file("extdata","c6.all.v5.1.symbols.gmt", package="BloodCancerMultiOmics2017"),
             KEGG=system.file("extdata","c2.cp.kegg.v5.1.symbols.gmt", package = "BloodCancerMultiOmics2017"))

DEs <- list()
DEs$expression$nut <- expr_nut
DEs$expression$TP53 <- expr_TP53
DEs$methylation$nut <- meth_nut
DEs$methylation$TP53 <- meth_TP53
pathways <- DEs %>% map(function(x) x %>% map(function(y) names(gmts) %>% map(function(z) enricher(y, z, z))))

pathways <- names(DEs) %>% map(function(x) names(DEs[[x]]) %>% map(function(y) names(gmts) %>% map(function(z) enricher(DEs[[x]][[y]], paste(x, y), z)))) 
pathways[[1]][[1]] %>% map(function(x) plot(x[["enBar"]]))
pathways[[1]][[2]] %>% map(function(x) plot(x[["enBar"]]))
pathways[[2]][[1]] %>% map(function(x) plot(x[["enBar"]]))
pathways[[2]][[2]] %>% map(function(x) plot(x[["enBar"]]))
resss <- 1:2 %>% map(function(x) 1:2 %>% map(function(y) 1:3 %>% map(function(z) path.sel(pathways[[x]][[y]][[z]]$rg[[1]]))))
ress <- resss %>% map(function(x) x %>% map(function(y) unlist(y)))


vennList <- Venn(list(methylation_nut = ress[[2]][[1]] , methylation_TP53 = ress[[2]][[2]], expression_nut = ress[[1]][[1]], expression_TP53 = ress[[1]][[2]]))
Vennerable::plot(vennList, doWeights = F, type = "ellipses", show = list(Faces = FALSE))

upset(fromList(list(methylation_nut = ress[[2]][[1]] , methylation_TP53 = ress[[2]][[2]], expression_nut = ress[[1]][[1]], expression_TP53 = ress[[1]][[2]])), order.by = "freq", number.angles = 30, point.size = 3.5, line.size = 2, sets.bar.color = "blue")

Reduce(intersect, list(methylation_nut = ress[[2]][[1]] , methylation_TP53 = ress[[2]][[2]], expression_nut = ress[[1]][[1]], expression_TP53 = ress[[1]][[2]]))
```


# Analysis of Elastic Net Coefficients


## With drugs

### Discrete
200 runs
```{r fig.height=15, message=FALSE, warning=FALSE, paged.print=FALSE}
# fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
feature.df <- muvis::data_preproc(feature.df)

# with drugs
fdf <- feature.df[,-which((colnames(feature.df) %in% c("Nutlin.3a", "TP53", "nut", "del17p")))]
fdf <- scale(data.matrix(fdf))
fdf <- fdf[, colSums(is.na(fdf)) != nrow(fdf)]
lambdas <- (seq(0,2000,10)/100000) * 5 + 0.0001
cfs <- 1:200 %>% map(function(x) sel.nut(df = fdf, nut = feature.df$nut, TP53 = feature.df$TP53, alpha = 0.8, lambda = lambdas[x], spl = 0.75)) %>% map(function(x) data.matrix(x)[,1])
means <- tapply(unlist(cfs), names(unlist(cfs)), mean)
ses <- tapply(unlist(cfs), names(unlist(cfs)), sd)
sel.rates <- tapply(unlist(cfs), names(unlist(cfs)), sel.rate)
ord <- order(means)
dat <- data.frame(feature = names(means)[ord], mean = means[names(means)[ord]], sel.rate = sel.rates[names(means)[ord]], ses = ses[names(means)[ord]])
dat <- dat[dat$mean != 0,]
#dat <- dat[-grep("ENS",dat$feature),]
dat %>% arrange(mean) -> dat
dat$feature <- factor(dat$feature, levels = dat$feature)
ggplot(dat, aes(x=feature, weight=mean, fill = sel.rate/200)) + geom_bar() + coord_flip() +labs(y = "mean coefficient", fill = "selection frequency") 
ML.drug.p.features.disc <- as.character(dat$feature)
write(ML.drug.p.features.disc, "../results/ML_drug_disc.txt")
ML.drug.p.features.disc <- read.table("../results/ML_drug_disc.txt")
ML.drug.p.features.disc <- ML.drug.p.features.disc[,1]
```


### Continuous
```{r fig.height=20, message=FALSE, warning=FALSE, paged.print=FALSE}
# fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
feature.df <- muvis::data_preproc(feature.df)

# with drugs
fdf <- feature.df[,-which((colnames(feature.df) %in% c("Nutlin.3a", "TP53", "nut", "del17p")))]
fdf <- scale(data.matrix(fdf))
fdf <- fdf[, colSums(is.na(fdf)) != nrow(fdf)]
lambdas <- (seq(0,2000,10)/100000) * 5 + 0.0001
cfs <- 1:200 %>% map(function(x) sel.Nutlin(df = fdf, nut = feature.df$Nutlin.3a, TP53 = feature.df$TP53, alpha = 0.8, lambda = lambdas[x], spl = 0.75)) %>% map(function(x) data.matrix(x)[,1])
means <- tapply(unlist(cfs), names(unlist(cfs)), mean)
ses <- tapply(unlist(cfs), names(unlist(cfs)), sd)
sel.rates <- tapply(unlist(cfs), names(unlist(cfs)), sel.rate)
ord <- order(means)
dat <- data.frame(feature = names(means)[ord], mean = means[names(means)[ord]], sel.rate = sel.rates[names(means)[ord]], ses = ses[names(means)[ord]])
dat <- dat[dat$mean != 0,]
#dat <- dat[-grep("ENS",dat$feature),]
dat %>% arrange(mean) -> dat
dat$feature <- factor(dat$feature, levels = dat$feature)
ggplot(dat, aes(x=feature, weight=mean, fill = sel.rate/200)) + geom_bar() + coord_flip() +labs(y = "mean coefficient", fill = "selection frequency") 
ML.drug.p.features.cont <- as.character(dat$feature)
write(ML.drug.p.features.cont, "../results/ML_drug_cont.txt")
ML.drug.p.features.cont <- read.table("../results/ML_drug_cont.txt")
ML.drug.p.features.cont <- ML.drug.p.features.cont[,1]
```


## Without Drugs

### Discrete
200 runs
```{r fig.height=20, message=FALSE, warning=FALSE, paged.print=FALSE}
sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
feature.df <- muvis::data_preproc(feature.df)

# without drugs
fdf <- feature.df[,-which((colnames(feature.df) %in% c("Nutlin.3a", "TP53", "nut", "del17p")))]
fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
fdf <- scale(data.matrix(fdf))
fdf <- fdf[, colSums(is.na(fdf)) != nrow(fdf)]
lambdas <- (seq(0,2000,10)/100000) * 5 + 0.0001
cfs <- 1:200 %>% map(function(x) sel.nut(df = fdf, nut = feature.df$nut, TP53 = feature.df$TP53, alpha = 0.8, lambda = lambdas[x], spl = 0.75)) %>% map(function(x) data.matrix(x)[,1])
means <- tapply(unlist(cfs), names(unlist(cfs)), mean)
ses <- tapply(unlist(cfs), names(unlist(cfs)), sd)
sel.rates <- tapply(unlist(cfs), names(unlist(cfs)), sel.rate)
ord <- order(means)
dat <- data.frame(feature = names(means)[ord], mean = means[names(means)[ord]], sel.rate = sel.rates[names(means)[ord]], ses = ses[names(means)[ord]])
dat <- dat[dat$mean != 0,]
dat %>% arrange(mean) -> dat
dat$feature <- factor(dat$feature, levels = dat$feature)
ggplot(dat, aes(x=feature, weight=mean, fill = sel.rate/200)) + geom_bar() + coord_flip() +labs(y = "mean coefficient", fill = "selection frequency") 
ML.drug.n.features.disc <- as.character(dat$feature)
write(ML.drug.n.features.disc, "../results/ML_disc.txt")
ML.drug.n.features.disc <- read.table("../results/ML_disc.txt")
ML.drug.n.features.disc <- ML.drug.n.features.disc[,1]
```


### Continuous
200 runs
```{r fig.height=20, message=FALSE, warning=FALSE, paged.print=FALSE}
# fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
feature.df <- muvis::data_preproc(feature.df)

# without drugs
fdf <- feature.df[,-which((colnames(feature.df) %in% c("Nutlin.3a", "TP53", "nut", "del17p")))]
fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
fdf <- scale(data.matrix(fdf))
fdf <- fdf[, colSums(is.na(fdf)) != nrow(fdf)]
lambdas <- (seq(0,2000,10)/100000) * 5 + 0.0001
cfs <- 1:200 %>% map(function(x) sel.Nutlin(df = fdf, nut = feature.df$Nutlin.3a, TP53 = feature.df$TP53, alpha = 0.8, lambda = lambdas[x], spl = 0.75)) %>% map(function(x) data.matrix(x)[,1])
means <- tapply(unlist(cfs), names(unlist(cfs)), mean)
ses <- tapply(unlist(cfs), names(unlist(cfs)), sd)
sel.rates <- tapply(unlist(cfs), names(unlist(cfs)), sel.rate)
ord <- order(means)
dat <- data.frame(feature = names(means)[ord], mean = means[names(means)[ord]], sel.rate = sel.rates[names(means)[ord]], ses = ses[names(means)[ord]])
dat <- dat[dat$mean != 0,]
#dat <- dat[-grep("ENS",dat$feature),]
dat %>% arrange(mean) -> dat
dat$feature <- factor(dat$feature, levels = dat$feature)
ggplot(dat, aes(x=feature, weight=mean, fill = sel.rate/200)) + geom_bar() + coord_flip() +labs(y = "mean coefficient", fill = "selection frequency") 
ML.drug.n.features.cont <- as.character(dat$feature)
write(ML.drug.n.features.cont, "../results/ML_cont.txt")
ML.drug.n.features.cont <- read.table("../results/ML_cont.txt")
ML.drug.n.features.cont <- ML.drug.n.features.cont[,1]
```

# IC50 Nutlin Response
200 runs
```{r fig.height=20, message=FALSE, warning=FALSE, paged.print=FALSE}
# fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
sample.names <- intersect(rownames(drug_meta), colnames(exprMat))
sample.names <- sample.names[which(sample.names %in% rownames(ic50.data))]
feature.df <- cbind(drug_meta[sample.names,], t(exprMat[,sample.names]))
feature.df <- muvis::data_preproc(feature.df)


# without drugs
fdf <- feature.df[,-which((colnames(feature.df) %in% c("Nutlin.3a", "TP53", "nut", "del17p")))]
fdf <- fdf[,!(colnames(fdf) %in% make.names(colnames(cps.data)))]
fdf <- scale(data.matrix(fdf))
fdf <- fdf[, colSums(is.na(fdf)) != nrow(fdf)]
lambdas <- (seq(0,2000,10)/100000) * 5 + 0.0001
cfs <- 1:200 %>% map(function(x) sel.Nutlin(df = fdf, nut = ic50.data[sample.names, "nutlin.3"], TP53 = feature.df$TP53, alpha = 0.8, lambda = lambdas[x], spl = 0.75)) %>% map(function(x) data.matrix(x)[,1])
means <- tapply(unlist(cfs), names(unlist(cfs)), mean)
ses <- tapply(unlist(cfs), names(unlist(cfs)), sd)
sel.rates <- tapply(unlist(cfs), names(unlist(cfs)), sel.rate)
ord <- order(means)
dat <- data.frame(feature = names(means)[ord], mean = means[names(means)[ord]], sel.rate = sel.rates[names(means)[ord]], ses = ses[names(means)[ord]])
dat <- dat[dat$mean != 0,]
#dat <- dat[-grep("ENS",dat$feature),]
dat %>% arrange(mean) -> dat
dat$feature <- factor(dat$feature, levels = dat$feature)
ggplot(dat, aes(x=feature, weight=mean, fill = sel.rate/200)) + geom_bar() + coord_flip() +labs(y = "mean coefficient", fill = "selection frequency") 
ML.IC50 <- as.character(dat$feature)
write(ML.IC50, "../results/ML_IC50.txt")
ML.IC50 <- read.table("../results/ML_IC50.txt")
ML.IC50 <- ML.IC50[,1]
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
vennList <- Venn(list(DA = DA.features , ML_with_drug = ML.drug.p.features.cont, ML_without_drug = ML.drug.n.features.cont, ML_IC50 = ML.IC50))
Vennerable::plot(vennList, doWeights = F, type = "ellipses", show = list(Faces = FALSE))

upset(fromList(list(DA = DA.features , ML_with_drug = ML.drug.p.features.cont, ML_without_drug = ML.drug.n.features.cont, ML_IC50 = ML.IC50)), order.by = "freq", number.angles = 30, point.size = 3.5, line.size = 2, sets.bar.color = "blue")

imp.genes <- Reduce(intersect, list(DA.features,  ML.drug.p.features.cont, ML.drug.n.features.cont, ML.IC50))
Reduce(intersect, list(ML.drug.p.features.cont, ML.drug.n.features.cont, ML.IC50))
```

